### ISSUE TITLE
Feature request: Promps

### ISSUE THREAD

**Issue by Cre8tiveDigital** [markhuge/grunt-mailgun#18]
Hi, I have recently started using grunt-mailgun and it's amazing saves me so much time. one thing I have come across tho is sometimes when I build email's I have multiple versions of the same email. And when I call grunt-mailgun all the different versions are sent (Great news), my issue is if I have some changes to do on one email I would need to resend a test but I would only want to send the one email i have amended is there a way you could add a prompt in to the task to ask which email you would like to send or all of them. 

Thanks

**Comment by markhuge** [comment]
Hey! Happy you find this useful! Unfortunately I haven't used grunt in years, and I forget how grunt works, so I don't plan on adding new features.

With that said, gulp is actually a lot nicer for this kinda thing, because you can chain together whatever conditions upstream, rather than having to hard code globs of src files. A dude ported this whole workflow to gulp a few years back: https://www.npmjs.com/package/gulp-mailgun

I'm sure you can find a gulp plugin that only passes along modified files to the next thing in the chain.
