### ISSUE TITLE
Cache Busting Subject Line

### ISSUE THREAD

**Issue by Ethanhackett** [markhuge/grunt-mailgun#8]
Some mail clients group emails of the same subject line together which can cause testing issues.

If you're testing an email and mail yourself a test, then modify the test and email it again the grouping process can conflict css wise and run into previewing issues. 

It would be nice for testing purposes if there could be a cache busting feature that appends either a timestamp or random number to the end of an email subject line so that emails don't get automatically grouped together while testing.

**Comment by markhuge** [comment]
It sounds like you're looking for an option to prevent conversation threading. Is that correct?

**Comment by Ethanhackett** [comment]
Yes

Ethan Hackett

**Comment by markhuge** [comment]
This actually ends up being an interesting problem. There isn't a standard threading model, so disparate email clients tend to handle it differently.

There's 4 things (that I'm aware of) that different clients use for conversation threading:

- subject (+/- "re:" "fwd:")
- In-Reply-To header
- participants
- context

In order to guarantee the intended behavior on most clients, we'd need to vary the subject, sender, and add the In-Reply-To header. All totally doable, but I don't know if having to change things other than the subject would break your use case.

**Comment by Ethanhackett** [comment]
I notice it happening in Apple mail and Gmail on mobile and desktop. Simply changing the subject line in grunt seems to fix it in my situation. Maybe if it had the option "thread-buster" and then the value could be, subject, header, all.

Then the use case would be flexible if someone only wants to turn on or off one threading behavior.

I don't know how you would very participants other than emailing a random email like 329423@domain.com or something.

I guess it really depends on how maligun is being used. I use it for testing my email templates but others might use it for legitimate distribution and thread-busting might not be good.
